### ISSUE TITLE
AttributeError: 'Admob' object has no attribute '_adview'

### ISSUE THREAD

**Issue by pihash252** [ziyaad30/KivyBannerMob#1]
This showed in my logcat. Apparently, line 114 in your `__init__.py` is the reason. Kindly check and tell how it can be resolved.

**Comment by ziyaad30** [comment]
Hi, as much as I would like to help you, I have not updated this repository for a long time, due to working away from home. I actually need to archive this....

Have a look at this: https://github.com/MichaelStott/KivMob instead

Apologies friend!!!
